config/routes.rb
Rails.application.routes.draw do
  root "restaurants#index"
  resources :restaurants, only: %i[new create edit update destroy show] do
    collection do
    end
    resources :reviews, only: %i[new create]
  end
  # resources :reviews, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian],
  message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to root_path
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[edit update destroy ]
  before_action :set_restaurant, only: %i[new create]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restuarants_helper.rb
module RestuarantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
<div class="container">
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary"%>
  </div>
</div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= restaurant.phone_number %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= restaurant.category %>
  </p>

</div>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restuarant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants List:</h1>
  <hr>
  <% @restaurants.each do |restaurant| %>
  <div class="my-2">
  <div class="d-flex align-items-center">
    <h2><%= restaurant.name %></h2>
    <p class="px-4 m-0"><%= restaurant.category %></p>
  </div>
    <%= link_to "See Details", restaurant_path(restaurant) %>
    <hr>
  </div>
  <% end %>

  <div class="actions">
  <p><%= link_to "Add Restaurant", new_restaurant_path %></p>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>New restuarant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restuarants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<%= link_to "Review this restaurant", new_restaurant_review_path(@restaurant) %> |
<h2>Reviews</h2>
<% @restaurant.reviews.each do |review| %>
<%= render "reviews/review" , review: review%>
<% end %>
<div>
  <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %> |
  <%= link_to "Back to restaurants", root_path %>

  <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review], url:restaurant_reviews_path(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :rating %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary"%>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= review.content %>
  </p>

</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to Restaurant", reviews_path %>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to restaurant",  restaurant_path(@restaurant) %>
</div>